-- MySQL Script generated by MySQL Workbench
-- Mon Apr  5 14:59:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema home
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema home
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `home` DEFAULT CHARACTER SET utf8 ;
USE `home` ;

-- -----------------------------------------------------
-- Table `home`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `termsOfUse` CHAR(2) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_city1_idx` (`city_id` ASC) ,
  CONSTRAINT `fk_person_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `home`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`house` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `numberRooms` INT NOT NULL,
  `numberBathrooms` INT NOT NULL,
  `parking` CHAR(2) NOT NULL,
  `internetService` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` MEDIUMTEXT NOT NULL COMMENT 'URL de la imágen',
  `imgType` CHAR(1) NOT NULL DEFAULT 's' COMMENT 'imgType es paa saber si la imágen es de soporte o es principal.\nS para soporte y P para principal',
  `house_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_house1_idx` (`house_id` ASC) ,
  CONSTRAINT `fk_images_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `home`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`additionalServices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`additionalServices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `services` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`user` (
  `rol_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`rol_id`, `user_id`),
  INDEX `fk_rol_has_user_user1_idx` (`user_id` ASC) ,
  INDEX `fk_rol_has_user_rol_idx` (`rol_id` ASC) ,
  CONSTRAINT `fk_rol_has_user_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `home`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `home`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`booking` (
  `person_id` INT NOT NULL,
  `house_id` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`person_id`, `house_id`),
  INDEX `fk_person_has_house_house1_idx` (`house_id` ASC) ,
  INDEX `fk_person_has_house_person1_idx` (`person_id` ASC) ,
  CONSTRAINT `fk_person_has_house_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `home`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_house_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `home`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`.`serviceHome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home`.`serviceHome` (
  `house_id` INT NOT NULL,
  `additionalServices_id` INT NOT NULL,
  PRIMARY KEY (`house_id`, `additionalServices_id`),
  INDEX `fk_house_has_additionalServices_additionalServices1_idx` (`additionalServices_id` ASC) ,
  INDEX `fk_house_has_additionalServices_house1_idx` (`house_id` ASC) ,
  CONSTRAINT `fk_house_has_additionalServices_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `home`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_house_has_additionalServices_additionalServices1`
    FOREIGN KEY (`additionalServices_id`)
    REFERENCES `home`.`additionalServices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
